### ISSUE TITLE
<ERROR>: Failed to reload lockdownd service agents

### ISSUE THREAD

**Issue by krisanovdev** [DanyL/lockdownd_playground#2]
Hi!
I've got next error on iPhone 6s iOS 11.3
`<ERROR>: Failed to reload lockdownd service agents`

I saw your comments in code:
`/*
     lock the mutex here and call pthread_mutex_trylock until success or timeout.
     The callback will unlock the mutex once the notification has been received.
     */` and unfortunately I'm getting timeout every time.

Can you help me?
Is there are some preconditions to run launchdown?

**Comment by pappanunny** [comment]
I am also facing this issue. 

Below given is the error i receive for the input command :  launchdown -v1 test
Could see the timed out debug log

$ **./launchdown -v1 test**
 |---|---|---| [launchdown.c:run_service_agent():259] <INFO>: Uploading service agent: CC745AAC-339D-4945-8849-F9759DE02504
 |---|---|---| [launchdown.c:run_service_agent():265] <INFO>: Reloading lockdownd service agents
 |---|---|---|---|---| [device.c:observe_notification_with_timeout():463] <DEBUG>: **timed out**
 |---|---|---|---|---|---| [device.c:observe_notification_with_timeout_callback():398] <DEBUG>: Recevied notification:
 |---|---|---| [launchdown.c:run_service_agent():269] <ERROR>: Failed to reload lockdownd service agents

Device: **iPhone6S Plus**, iOS Version: **10.0.2**

**Comment by DanyL** [comment]
Hey @MrKris99 @pappanunny 

One of the flaws launchdown is based on is a misconfigured sandbox profile which allows launchdown-helper app to post a distributed notification with user info to eventually trigger the bug in lockdownd.

I don't have the ability to verify this but AFAIK this flaw was introduced with iOS 12.0 and thous wouldn't work on any version prior that.
