### ISSUE TITLE
Examples for patchy tool

### ISSUE THREAD

**Issue by krisanovdev** [DanyL/lockdownd_playground#3]
Hi, it would be really nice if you advice some examples (primitive) for patchy tool usage.

**Comment by DanyL** [comment]
Hey @MrKris99,

Patchy receives 2 arguments:
1. The original, properly signed and unpacked app
2. The patch, a directory structured the same as the original app but contains only the necessary sub-directories and the files you wish to replace.

For example, replacing the executable of the Files.app:
`> ./system_app_man down com.apple.DocumentsApp /tmp`
`> mkdir /tmp/patch`
`> cp [replacement executable] /tmp/patch/Files`
`> ./patchy /tmp/out/Files.app /tmp/patch`

Hope that helps, let me know if you have any additional questions or trouble using the tools.
